// Code generated by optgen; DO NOT EDIT.

package opt

const (
	UnknownOp Operator = iota

	VariableOp
	ConstOp
	PlaceholderOp
	ListOp
	OrderedListOp
	ProjectionsOp
	ExistsOp
	AndOp
	OrOp
	NotOp
	EqOp
	LtOp
	GtOp
	LeOp
	GeOp
	NeOp
	InOp
	NotInOp
	LikeOp
	NotLikeOp
	ILikeOp
	NotILikeOp
	SimilarToOp
	NotSimilarToOp
	RegMatchOp
	NotRegMatchOp
	RegIMatchOp
	NotRegIMatchOp
	IsDistinctFromOp
	IsNotDistinctFromOp
	IsOp
	IsNotOp
	AnyOp
	SomeOp
	AllOp
	BitandOp
	BitorOp
	BitxorOp
	PlusOp
	MinusOp
	MultOp
	DivOp
	FloorDivOp
	ModOp
	PowOp
	ConcatOp
	LShiftOp
	RShiftOp
	UnaryPlusOp
	UnaryMinusOp
	UnaryComplementOp
	FunctionOp
	TrueOp
	FalseOp
	ScanOp
	ValuesOp
	SelectOp
	ProjectOp
	InnerJoinOp
	LeftJoinOp
	RightJoinOp
	FullJoinOp
	SemiJoinOp
	AntiJoinOp
	InnerJoinApplyOp
	LeftJoinApplyOp
	RightJoinApplyOp
	FullJoinApplyOp
	SemiJoinApplyOp
	AntiJoinApplyOp
	GroupByOp
	UnionOp
	IntersectOp
	ExceptOp
	SortOp
)

const opNames = "unknownvariableconstplaceholderlistorderedListprojectionsexistsandornoteqltgtlegeneinnotInlikenotLikeiLikenotILikesimilarTonotSimilarToregMatchnotRegMatchregIMatchnotRegIMatchisDistinctFromisNotDistinctFromisisNotanysomeallbitandbitorbitxorplusminusmultdivfloorDivmodpowconcatlShiftrShiftunaryPlusunaryMinusunaryComplementfunctiontruefalsescanvaluesselectprojectinnerJoinleftJoinrightJoinfullJoinsemiJoinantiJoininnerJoinApplyleftJoinApplyrightJoinApplyfullJoinApplysemiJoinApplyantiJoinApplygroupByunionintersectexceptsort"

var opIndexes = [...]uint32{0, 7, 15, 20, 31, 35, 46, 57, 63, 66, 68, 71, 73, 75, 77, 79, 81, 83, 85, 90, 94, 101, 106, 114, 123, 135, 143, 154, 163, 175, 189, 206, 208, 213, 216, 220, 223, 229, 234, 240, 244, 249, 253, 256, 264, 267, 270, 276, 282, 288, 297, 307, 322, 330, 334, 339, 343, 349, 355, 362, 371, 379, 388, 396, 404, 412, 426, 439, 453, 466, 479, 492, 499, 504, 513, 519, 523}
