// Code generated by "stringer -type=operator operator.go"; DO NOT EDIT.

package main

import "fmt"

const _operator_name = "unknownOprootOpdefineSetOpdefineOpdefineFieldOpruleSetOpruleHeaderOpruleOpbindOprefOpmatchTemplateOpmatchNamesOpmatchInvokeOpmatchFieldsOpmatchAndOpmatchNotOpmatchAnyOpmatchListOpreplaceRootOpconstructOpconstructListOptagsOpstringOp"

var _operator_index = [...]uint8{0, 9, 15, 26, 34, 47, 56, 68, 74, 80, 85, 100, 112, 125, 138, 148, 158, 168, 179, 192, 203, 218, 224, 232}

func (i operator) String() string {
	if i < 0 || i >= operator(len(_operator_index)-1) {
		return fmt.Sprintf("operator(%d)", i)
	}
	return _operator_name[_operator_index[i]:_operator_index[i+1]]
}
