// Code generated by "stringer -type=Operator operator.go"; DO NOT EDIT.

package optgen

import "strconv"

const _Operator_name = "UnknownOpRootOpDefineSetOpDefineOpDefineFieldOpRuleSetOpRuleHeaderOpRuleOpBindOpRefOpMatchTemplateOpMatchTemplateNamesOpMatchInvokeOpMatchFieldsOpMatchAndOpMatchNotOpMatchAnyOpMatchListOpReplaceRootOpConstructOpConstructListOpTagsOpStringOpOpNameOp"

var _Operator_index = [...]uint8{0, 9, 15, 26, 34, 47, 56, 68, 74, 80, 85, 100, 120, 133, 146, 156, 166, 176, 187, 200, 211, 226, 232, 240, 248}

func (i Operator) String() string {
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
